Project document
ta-assistant/TA-CLI pull request #60
Opened 2021-07-22 15:19 UTC by vitvara

adding document

2021-07-22 16:16 UTC, abounk approved these changes
👍👍👍

2021-07-22 16:20 UTC, Tanidean requested changes

2021-07-22 16:20 UTC, Tanidean commented on README.md
> +> in this line you can choose read or fetch upto you
***up to you

2021-07-22 16:20 UTC, Tanidean commented on README.md
> +<p align="center">This program is about checking students work in ta's computer and send students score to server by CLI</p>
better use ***Teacher assistant(TA)'s computer than ***ta's computer

2021-07-23 03:59 UTC, Tanidean approved these changes

2021-07-23 06:25 UTC, closed without merging